### ISSUE TITLE
Usable with GDScript

### ISSUE THREAD

**Issue by jokeruarwentto** [pkdawson/imgui-godot#16]
Title says all, it is possible to get a usable version for GDScript?
Thanks

**Comment by pkdawson** [comment]
I haven't tried it, but someone else made a C++ module for this for Godot 3.x:
https://github.com/Blackdrop-Interactive-AB/godot-dear-imgui/

Making GDScript bindings currently requires a C++ module or GDExtension, which I'm not doing because it's more complicated for everyone to use.

However, C# GDExtension support is [planned for Godot 4](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-1):
> One of the big changes that we are still working on is support for writing GDExtensions in C#. With GDExtension, C# classes will be registered in the engine and work as the built-in classes do, which should improve the support of C# nodes and resources throughout the engine.

With that, I think I could make a good GDScript interface. Though it's not simple, because GDScript doesn't really have pointer/reference types for parameters, which the Dear ImGui API uses a lot.

So I'm leaving this issue open, but I have to wait for that. Not sure if that will be in Godot 4.0, or 4.1 or later.

**Comment by pkdawson** [comment]
Implemented in v5.0.0
