### ISSUE TITLE
Android build (non-desktop) breaks addon

### ISSUE THREAD

**Issue by PerfectlyFineCode** [pkdawson/imgui-godot#65]
Android build breaks addon completely.
From what I understand there's no way to use platform-specific code either.
I have even added code to check for OS and/or feature flags to no avail. Still breaks.
What can be done to fix this?

**Godot Version**
v4.2.2.stable.official [15073afe3]

**Addon Version**
5.1.0

![image](https://github.com/pkdawson/imgui-godot/assets/70201838/6cdc42f3-7d1d-4a3a-a297-b22f02c27ae3)

**Comment by pkdawson** [comment]
This plugin doesn't currently support Android (or iOS), though actually that's something I could probably do for GDScript and C++, just not C#.

This is a hacky solution, but it's the best I've got so far: use a feature flag, and then wherever you use ImGui, do this first:
```gdscript
var ImGui = ClassDB.instantiate("ImGui")
```

You'll get a warning (SHADOWED_GLOBAL_IDENTIFIER), but the code should compile.

Otherwise my notes here apply (I still need to update the documentation/examples):
https://github.com/pkdawson/imgui-godot/discussions/62#discussioncomment-9630061

**Comment by pkdawson** [comment]
OK, better solution. Try this:

```gdscript
var ImGui = Engine.has_singleton("ImGuiGD")
if ImGui:
    ImGui.Begin("hello")
    ImGui.End()
```

You still get the warning, but no leaks and you shouldn't even need a feature flag.

**Comment by PerfectlyFineCode** [comment]
> OK, better solution. Try this:
> 
> ```gdscript
> var ImGui = Engine.has_singleton("ImGuiGD")
> if ImGui:
>     ImGui.Begin("hello")
>     ImGui.End()
> ```
> 
> You still get the warning, but no leaks and you shouldn't even need a feature flag.
> 
> I'll add a slightly better solution in the next version, which has the same drawbacks but is less weird and broken than exploiting a bool like this.

Amazing!
It worked. Thank you.

**Comment by pkdawson** [comment]
Starting with imgui-godot v6.0.0, the preferred solution is:

```gdscript
if Engine.has_singleton("ImGuiAPI"):
    var ImGui: Object = Engine.get_singleton("ImGuiAPI")
    ImGui.Begin("hello")
    ImGui.End()
```

See [Export](https://github.com/pkdawson/imgui-godot/wiki/Export)
